import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Go Carte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="max-w-6xl mx-auto py-5 px-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
